#host env vars work here too i.e. !ENV ${Hostname}

telegraf:
    host: 10.10.10.42
    port: 8092

pi:
    host: 10.10.10.196
    piname: 'pizero'


pulse:
    GPIO2: 
        pin: 'GPIO2'
        utility: 'water'
        metername: 'outside'
    GPIO3:
        pin: 'GPIO3'
        utility: 'water'
        metername: 'inside'
