#host env vars work here too i.e. !ENV ${Hostname}

telegraf:
    host: 10.10.10.42
    port: 8092

pi:
    host: 10.10.10.196
    piname: !ENV ${piname}


pulse:
    GPIO2: 
        pin: !ENV ${pulse_GPIO2_pin}
        utility: !ENV ${pulse_GPIO2_utility}
        metername: !ENV ${pulse_GPIO2_metername}
        unit: !ENV ${pulse_GPIO2_unit}
    GPIO3:
        pin: !ENV ${pulse_GPIO3_pin}
        utility: !ENV ${pulse_GPIO3_utility}
        metername: !ENV ${pulse_GPIO3_metername}
        unit: !ENV ${pulse_GPIO3_unit}
